name = "trini-proxy"
main = "src/worker.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "threats-db"
database_id = "__PASTE_D1_ID__"

[[kv_namespaces]]
binding = "KV"
id = "__PASTE_KV_ID__"
